baseURL = "https://anahitakarandikar.github.io/"
languageCode = "en-us"
title = "Anahita Karandikar"
theme = "academimal"

[params]
  author = "Anahita Karandikar"
  description = "PhD Candidate in Economics, UBC"
  bio = "PhD Candidate in Economics, UBC"
  avatar = "img/profile.jpg"

[params.social]
  github = "https://github.com/anahitakarandikar"
  linkedin = "https://www.linkedin.com/in/anahita-karandikar-91412611a/"
  twitter = "https://x.com/anahitark"
  instagram = "https://www.instagram.com/anahitakarandikar/"
  bluesky = "https://bsky.app/profile/anahitark.bsky.social"
  google_scholar = "https://scholar.google.ca/citations?hl=en&user=Ns9TLa0AAAAJ"


[menu]
  [[menu.main]]
    name = "Home"
    url = "/"
    weight = 1

  [[menu.main]]
    name = "CV"
    url = "files/CV.pdf"
    weight = 2

  [[menu.main]]
    name = "Research"
    url = "/research/"
    weight = 3

  [[menu.main]]
    name = "Women in Econ/Policy"
    url = "/women/"
    weight = 4

  [[menu.main]]
    name = "Coffee & Croissants"
    url = "/coffee/"
    weight = 5

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true